gx.evt.autoSkip = false;
gx.define('wwpbaseobjects.notifications.common.wwp_masterpagenotificationswc', true, function (CmpContext) {
   this.ServerClass =  "wwpbaseobjects.notifications.common.wwp_masterpagenotificationswc" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.setCmpContext(CmpContext);
   this.ReadonlyForm = true;
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV6SDTNotificationsData=gx.fn.getControlValue("vSDTNOTIFICATIONSDATA") ;
      this.AV5IsAuthorized_CheckAllNotif=gx.fn.getControlValue("vISAUTHORIZED_CHECKALLNOTIF") ;
      this.AV6SDTNotificationsData=gx.fn.getControlValue("vSDTNOTIFICATIONSDATA") ;
   };
   this.e11262_client=function()
   {
      return this.executeServerEvent("'DOCHECKALLNOTIF'", false, null, false, false);
   };
   this.e12262_client=function()
   {
      return this.executeServerEvent("NOTIFICATIONITEM.CLICK", true, arguments[0], false, true);
   };
   this.e16262_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e17262_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,41,42,43,44,45];
   this.GXLastCtrlId =45;
   this.GridsdtnotificationsdatasContainer = new gx.grid.grid(this, 2,"WbpLvl2",15,"Gridsdtnotificationsdatas","Gridsdtnotificationsdatas","GridsdtnotificationsdatasContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.notifications.common.wwp_masterpagenotificationswc",[],true,1,false,true,0,false,false,false,"CollWWPBaseObjects\Notifications\Common\WWP_SDTNotificationsData.WWP_SDTNotificationsDataItem",0,"px",0,"px","Novo registro",false,false,false,null,null,false,"AV6SDTNotificationsData",true,[1,1,1,1],false,0,false,false);
   var GridsdtnotificationsdatasContainer = this.GridsdtnotificationsdatasContainer;
   GridsdtnotificationsdatasContainer.startDiv(16,"Unnamedtablefsgridsdtnotificationsdatas","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(17,"","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(18,"","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(19,"Notificationitem","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(20,"","0px","0px");
   GridsdtnotificationsdatasContainer.addTextBlock('NOTIFICATIONITEMICON',null,21);
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.startDiv(22,"","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(23,"Unnamedtable2","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(24,"","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(25,"","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(26,"","0px","0px");
   GridsdtnotificationsdatasContainer.addLabel();
   GridsdtnotificationsdatasContainer.addMultipleLineEdit("GXV2",27,"SDTNOTIFICATIONSDATA__NOTIFICATIONTITLE","","NotificationTitle","svchar",80,"chr",3,"row","200",200,"left",null,true,false,0,"");
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.startDiv(28,"","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(29,"","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(30,"","0px","0px");
   GridsdtnotificationsdatasContainer.addLabel();
   GridsdtnotificationsdatasContainer.addMultipleLineEdit("GXV3",31,"SDTNOTIFICATIONSDATA__NOTIFICATIONDESCRIPTION","","NotificationDescription","svchar",80,"chr",3,"row","200",200,"left",null,true,false,0,"");
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.startDiv(32,"","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(33,"","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(34,"","0px","0px");
   GridsdtnotificationsdatasContainer.addLabel();
   GridsdtnotificationsdatasContainer.addSingleLineEdit("GXV4",35,"SDTNOTIFICATIONSDATA__NOTIFICATIONDATETIME","","","NotificationDatetime","dtime",14,"chr",14,14,"right",null,[],"GXV4","GXV4",true,5,false,false,"NotificationItemDatetime",1,"");
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.startDiv(36,"","0px","0px");
   GridsdtnotificationsdatasContainer.startDiv(37,"","0px","0px");
   GridsdtnotificationsdatasContainer.startTable("Unnamedtablecontentfsgridsdtnotificationsdatas",38,"0px");
   GridsdtnotificationsdatasContainer.startRow("","","","","","");
   GridsdtnotificationsdatasContainer.startCell("","","","","","","","","","");
   GridsdtnotificationsdatasContainer.startDiv(41,"","0px","0px");
   GridsdtnotificationsdatasContainer.addLabel();
   GridsdtnotificationsdatasContainer.addSingleLineEdit("GXV5",42,"SDTNOTIFICATIONSDATA__NOTIFICATIONID","","","NotificationId","int",5,"chr",5,5,"right",null,[],"GXV5","GXV5",true,0,false,false,"Attribute",1,"");
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endCell();
   GridsdtnotificationsdatasContainer.endRow();
   GridsdtnotificationsdatasContainer.endTable();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   GridsdtnotificationsdatasContainer.endDiv();
   this.GridsdtnotificationsdatasContainer.emptyText = "";
   this.setGrid(GridsdtnotificationsdatasContainer);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"UNNAMEDTABLE1",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"NOTIFICATIONCONTENT",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[12]={ id: 12, fld:"NOTIFICATIONTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[13]={ id: 13, fld:"",grid:0};
   GXValidFnc[14]={ id: 14, fld:"",grid:0};
   GXValidFnc[16]={ id: 16, fld:"UNNAMEDTABLEFSGRIDSDTNOTIFICATIONSDATAS",grid:15};
   GXValidFnc[17]={ id: 17, fld:"",grid:15};
   GXValidFnc[18]={ id: 18, fld:"",grid:15};
   GXValidFnc[19]={ id: 19, fld:"NOTIFICATIONITEM",grid:15,evt:"e12262_client"};
   GXValidFnc[20]={ id: 20, fld:"",grid:15};
   GXValidFnc[21]={ id: 21, fld:"NOTIFICATIONITEMICON", format:2,grid:15, ctrltype: "textblock"};
   GXValidFnc[22]={ id: 22, fld:"",grid:15};
   GXValidFnc[23]={ id: 23, fld:"UNNAMEDTABLE2",grid:15};
   GXValidFnc[24]={ id: 24, fld:"",grid:15};
   GXValidFnc[25]={ id: 25, fld:"",grid:15};
   GXValidFnc[26]={ id: 26, fld:"",grid:15};
   GXValidFnc[27]={ id:27 ,lvl:2,type:"svchar",len:200,dec:0,sign:false,ro:1,isacc:0, multiline:true,grid:15,gxgrid:this.GridsdtnotificationsdatasContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTNOTIFICATIONSDATA__NOTIFICATIONTITLE",gxz:"ZV12GXV2",gxold:"OV12GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV2=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV12GXV2=Value},v2c:function(row){gx.fn.setGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONTITLE",row || gx.fn.currentGridRowImpl(15),gx.O.GXV2,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV2=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONTITLE",row || gx.fn.currentGridRowImpl(15))},nac:gx.falseFn};
   GXValidFnc[28]={ id: 28, fld:"",grid:15};
   GXValidFnc[29]={ id: 29, fld:"",grid:15};
   GXValidFnc[30]={ id: 30, fld:"",grid:15};
   GXValidFnc[31]={ id:31 ,lvl:2,type:"svchar",len:200,dec:0,sign:false,ro:1,isacc:0, multiline:true,grid:15,gxgrid:this.GridsdtnotificationsdatasContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTNOTIFICATIONSDATA__NOTIFICATIONDESCRIPTION",gxz:"ZV13GXV3",gxold:"OV13GXV3",gxvar:"GXV3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV3=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV13GXV3=Value},v2c:function(row){gx.fn.setGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONDESCRIPTION",row || gx.fn.currentGridRowImpl(15),gx.O.GXV3,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV3=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONDESCRIPTION",row || gx.fn.currentGridRowImpl(15))},nac:gx.falseFn};
   GXValidFnc[32]={ id: 32, fld:"",grid:15};
   GXValidFnc[33]={ id: 33, fld:"",grid:15};
   GXValidFnc[34]={ id: 34, fld:"",grid:15};
   GXValidFnc[35]={ id:35 ,lvl:2,type:"dtime",len:8,dec:5,sign:false,ro:1,isacc:0,grid:15,gxgrid:this.GridsdtnotificationsdatasContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTNOTIFICATIONSDATA__NOTIFICATIONDATETIME",gxz:"ZV14GXV4",gxold:"OV14GXV4",gxvar:"GXV4",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/99 99:99",dec:5},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.GXV4=gx.fn.toDatetimeValue(Value,"Y4MD")},v2z:function(Value){if(Value!==undefined)gx.O.ZV14GXV4=gx.fn.toDatetimeValue(Value)},v2c:function(row){gx.fn.setGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONDATETIME",row || gx.fn.currentGridRowImpl(15),gx.O.GXV4,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV4=gx.fn.toDatetimeValue(this.val(row))},val:function(row){return gx.fn.getGridDateTimeValue("SDTNOTIFICATIONSDATA__NOTIFICATIONDATETIME",row || gx.fn.currentGridRowImpl(15))},nac:gx.falseFn};
   GXValidFnc[36]={ id: 36, fld:"",grid:15};
   GXValidFnc[37]={ id: 37, fld:"",grid:15};
   GXValidFnc[38]={ id: 38, fld:"UNNAMEDTABLECONTENTFSGRIDSDTNOTIFICATIONSDATAS",grid:15};
   GXValidFnc[41]={ id: 41, fld:"",grid:15};
   GXValidFnc[42]={ id:42 ,lvl:2,type:"int",len:5,dec:0,sign:false,pic:"ZZZZ9",ro:1,isacc:0,grid:15,gxgrid:this.GridsdtnotificationsdatasContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTNOTIFICATIONSDATA__NOTIFICATIONID",gxz:"ZV15GXV5",gxold:"OV15GXV5",gxvar:"GXV5",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.GXV5=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV15GXV5=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONID",row || gx.fn.currentGridRowImpl(15),gx.O.GXV5,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV5=gx.num.intval(this.val(row))},val:function(row){return gx.fn.getGridIntegerValue("SDTNOTIFICATIONSDATA__NOTIFICATIONID",row || gx.fn.currentGridRowImpl(15),'.')},nac:gx.falseFn};
   GXValidFnc[43]={ id: 43, fld:"",grid:0};
   GXValidFnc[44]={ id: 44, fld:"",grid:0};
   GXValidFnc[45]={ id: 45, fld:"BTNCHECKALLNOTIF",grid:0,evt:"e11262_client"};
   this.ZV12GXV2 = "" ;
   this.OV12GXV2 = "" ;
   this.ZV13GXV3 = "" ;
   this.OV13GXV3 = "" ;
   this.ZV14GXV4 = gx.date.nullDate() ;
   this.OV14GXV4 = gx.date.nullDate() ;
   this.ZV15GXV5 = 0 ;
   this.OV15GXV5 = 0 ;
   this.GXV2 = "" ;
   this.GXV3 = "" ;
   this.GXV4 = gx.date.nullDate() ;
   this.GXV5 = 0 ;
   this.AV6SDTNotificationsData = [ ] ;
   this.AV5IsAuthorized_CheckAllNotif = false ;
   this.Events = {"e11262_client": ["'DOCHECKALLNOTIF'", true] ,"e12262_client": ["NOTIFICATIONITEM.CLICK", true] ,"e16262_client": ["ENTER", true] ,"e17262_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRIDSDTNOTIFICATIONSDATAS_nFirstRecordOnPage'},{av:'GRIDSDTNOTIFICATIONSDATAS_nEOF'},{av:'sPrefix'},{av:'AV6SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:15,pic:''},{av:'nRC_GXsfl_15',ctrl:'GRIDSDTNOTIFICATIONSDATAS',prop:'GridRC'},{av:'AV5IsAuthorized_CheckAllNotif',fld:'vISAUTHORIZED_CHECKALLNOTIF',pic:'',hsh:true}],[{av:'gx.fn.getCtrlProperty("NOTIFICATIONTITLE","Caption")',ctrl:'NOTIFICATIONTITLE',prop:'Caption'},{av:'gx.fn.getCtrlProperty("GRIDSDTNOTIFICATIONSDATAS","Visible")',ctrl:'GRIDSDTNOTIFICATIONSDATAS',prop:'Visible'},{av:'AV5IsAuthorized_CheckAllNotif',fld:'vISAUTHORIZED_CHECKALLNOTIF',pic:'',hsh:true},{ctrl:'BTNCHECKALLNOTIF',prop:'Visible'}]];
   this.EvtParms["START"] = [[{av:'AV6SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:15,pic:''},{av:'GRIDSDTNOTIFICATIONSDATAS_nFirstRecordOnPage'},{av:'nRC_GXsfl_15',ctrl:'GRIDSDTNOTIFICATIONSDATAS',prop:'GridRC'},{av:'GRIDSDTNOTIFICATIONSDATAS_nEOF'},{av:'sPrefix'},{av:'AV5IsAuthorized_CheckAllNotif',fld:'vISAUTHORIZED_CHECKALLNOTIF',pic:'',hsh:true}],[{ctrl:'SDTNOTIFICATIONSDATA__NOTIFICATIONID',prop:'Visible'},{av:'AV6SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:15,pic:''},{av:'GRIDSDTNOTIFICATIONSDATAS_nFirstRecordOnPage'},{av:'nRC_GXsfl_15',ctrl:'GRIDSDTNOTIFICATIONSDATAS',prop:'GridRC'}]];
   this.EvtParms["GRIDSDTNOTIFICATIONSDATAS.LOAD"] = [[{av:'AV6SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:15,pic:''},{av:'GRIDSDTNOTIFICATIONSDATAS_nFirstRecordOnPage'},{av:'nRC_GXsfl_15',ctrl:'GRIDSDTNOTIFICATIONSDATAS',prop:'GridRC'}],[{av:'gx.fn.getCtrlProperty("NOTIFICATIONITEMICON","Caption")',ctrl:'NOTIFICATIONITEMICON',prop:'Caption'}]];
   this.EvtParms["'DOCHECKALLNOTIF'"] = [[{av:'GRIDSDTNOTIFICATIONSDATAS_nFirstRecordOnPage'},{av:'GRIDSDTNOTIFICATIONSDATAS_nEOF'},{av:'AV6SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:15,pic:''},{av:'nRC_GXsfl_15',ctrl:'GRIDSDTNOTIFICATIONSDATAS',prop:'GridRC'},{av:'AV5IsAuthorized_CheckAllNotif',fld:'vISAUTHORIZED_CHECKALLNOTIF',pic:'',hsh:true},{av:'sPrefix'}],[{av:'gx.fn.getCtrlProperty("NOTIFICATIONTITLE","Caption")',ctrl:'NOTIFICATIONTITLE',prop:'Caption'},{av:'gx.fn.getCtrlProperty("GRIDSDTNOTIFICATIONSDATAS","Visible")',ctrl:'GRIDSDTNOTIFICATIONSDATAS',prop:'Visible'},{av:'AV5IsAuthorized_CheckAllNotif',fld:'vISAUTHORIZED_CHECKALLNOTIF',pic:'',hsh:true},{ctrl:'BTNCHECKALLNOTIF',prop:'Visible'}]];
   this.EvtParms["NOTIFICATIONITEM.CLICK"] = [[{av:'AV6SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:15,pic:''},{av:'GRIDSDTNOTIFICATIONSDATAS_nFirstRecordOnPage'},{av:'nRC_GXsfl_15',ctrl:'GRIDSDTNOTIFICATIONSDATAS',prop:'GridRC'},{av:'GRIDSDTNOTIFICATIONSDATAS_nEOF'},{av:'sPrefix'},{av:'AV5IsAuthorized_CheckAllNotif',fld:'vISAUTHORIZED_CHECKALLNOTIF',pic:'',hsh:true}],[{av:'AV6SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:15,pic:''},{av:'GRIDSDTNOTIFICATIONSDATAS_nFirstRecordOnPage'},{av:'nRC_GXsfl_15',ctrl:'GRIDSDTNOTIFICATIONSDATAS',prop:'GridRC'}]];
   this.setVCMap("AV6SDTNotificationsData", "vSDTNOTIFICATIONSDATA", 0, "CollWWPBaseObjects\Notifications\Common\WWP_SDTNotificationsData.WWP_SDTNotificationsDataItem", 0, 0);
   this.setVCMap("AV5IsAuthorized_CheckAllNotif", "vISAUTHORIZED_CHECKALLNOTIF", 0, "boolean", 4, 0);
   this.setVCMap("AV6SDTNotificationsData", "vSDTNOTIFICATIONSDATA", 0, "CollWWPBaseObjects\Notifications\Common\WWP_SDTNotificationsData.WWP_SDTNotificationsDataItem", 0, 0);
   this.setVCMap("AV6SDTNotificationsData", "vSDTNOTIFICATIONSDATA", 0, "CollWWPBaseObjects\Notifications\Common\WWP_SDTNotificationsData.WWP_SDTNotificationsDataItem", 0, 0);
   GridsdtnotificationsdatasContainer.addRefreshingVar({rfrVar:"AV6SDTNotificationsData"});
   GridsdtnotificationsdatasContainer.addRefreshingVar({rfrVar:"AV5IsAuthorized_CheckAllNotif"});
   GridsdtnotificationsdatasContainer.addRefreshingParm({rfrVar:"AV6SDTNotificationsData"});
   GridsdtnotificationsdatasContainer.addRefreshingParm({rfrVar:"AV5IsAuthorized_CheckAllNotif"});
   this.addGridBCProperty("Sdtnotificationsdata", ["NotificationTitle"], this.GXValidFnc[27], "AV6SDTNotificationsData");
   this.addGridBCProperty("Sdtnotificationsdata", ["NotificationDescription"], this.GXValidFnc[31], "AV6SDTNotificationsData");
   this.addGridBCProperty("Sdtnotificationsdata", ["NotificationDatetime"], this.GXValidFnc[35], "AV6SDTNotificationsData");
   this.addGridBCProperty("Sdtnotificationsdata", ["NotificationId"], this.GXValidFnc[42], "AV6SDTNotificationsData");
   this.Initialize( );
});
