gx.evt.autoSkip = false;
gx.define('wwpbaseobjects.subscriptions.wwp_subscriptionssettingsbyrole', false, function () {
   this.ServerClass =  "wwpbaseobjects.subscriptions.wwp_subscriptionssettingsbyrole" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV41Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.A12WWPEntityName=gx.fn.getControlValue("WWPENTITYNAME") ;
      this.A10WWPEntityId=gx.fn.getIntegerValue("WWPENTITYID",'.') ;
      this.AV36WWPSubscriptionRoleId=gx.fn.getControlValue("vWWPSUBSCRIPTIONROLEID") ;
      this.AV41Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.A12WWPEntityName=gx.fn.getControlValue("WWPENTITYNAME") ;
      this.A10WWPEntityId=gx.fn.getIntegerValue("WWPENTITYID",'.') ;
      this.AV36WWPSubscriptionRoleId=gx.fn.getControlValue("vWWPSUBSCRIPTIONROLEID") ;
   };
   this.e17222_client=function()
   {
      this.clearMessages();
      this.createWebComponent('Grid_dwc','WWPBaseObjects.Subscriptions.WWP_SubscriptionsSettingsByRoleWC',[this.AV29WWPEntityId,this.AV17NotifShowOnlySubscribedEvents,this.AV36WWPSubscriptionRoleId]);
      this.refreshOutputs([{ctrl:'GRID_DWC'},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}]);
      this.OnClientEventEnd();
      return gx.$.Deferred().resolve();
   };
   this.e11222_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e12222_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e13222_client=function()
   {
      return this.executeServerEvent("VNOTIFSHOWONLYSUBSCRIBEDEVENTS.CLICK", true, null, false, true);
   };
   this.e18222_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e19222_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,29,30,31,33,34,36,37,38];
   this.GXLastCtrlId =38;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",26,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.subscriptions.wwp_subscriptionssettingsbyrole",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","Novo registro",true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addSingleLineEdit("Wwpentityname",27,"vWWPENTITYNAME","Entity","","WWPEntityName","svchar",0,"px",100,80,"left",null,[],"Wwpentityname","WWPEntityName",true,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit("Wwpentityid",28,"vWWPENTITYID","","","WWPEntityId","int",0,"px",10,10,"right",null,[],"Wwpentityid","WWPEntityId",false,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit("Detailwebcomponent",29,"vDETAILWEBCOMPONENT","","","DetailWebComponent","char",0,"px",20,20,"left","e17222_client",[],"Detailwebcomponent","DetailWebComponent",true,0,false,false,"Attribute",1,"WWIconActionColumn WCD_ActionColumn");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 32, 17, "DVelop_DVPaginationBar", "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "Página <CURRENT_PAGE> de <TOTAL_PAGES>", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV8GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV8GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV8GridCurrentPage); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV9GridPageCount', "vGRIDPAGECOUNT", 'SetPageCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV9GridPageCount=UC.GetPageCount();gx.fn.setControlValue("vGRIDPAGECOUNT",UC.ParentObject.AV9GridPageCount); });
   GRIDPAGINATIONBARContainer.setProp("RecordCount", "Recordcount", '', "str");
   GRIDPAGINATIONBARContainer.setProp("Page", "Page", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV38GridAppliedFilters', "vGRIDAPPLIEDFILTERS", 'SetAppliedFilters');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV38GridAppliedFilters=UC.GetAppliedFilters();gx.fn.setControlValue("vGRIDAPPLIEDFILTERS",UC.ParentObject.AV38GridAppliedFilters); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e11222_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e12222_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DVPANEL_UNNAMEDTABLE1Container = gx.uc.getNew(this, 9, 0, "BootstrapPanel", "DVPANEL_UNNAMEDTABLE1Container", "Dvpanel_unnamedtable1", "DVPANEL_UNNAMEDTABLE1");
   var DVPANEL_UNNAMEDTABLE1Container = this.DVPANEL_UNNAMEDTABLE1Container;
   DVPANEL_UNNAMEDTABLE1Container.setProp("Class", "Class", "", "char");
   DVPANEL_UNNAMEDTABLE1Container.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_UNNAMEDTABLE1Container.setProp("Width", "Width", "100%", "str");
   DVPANEL_UNNAMEDTABLE1Container.setProp("Height", "Height", "100", "str");
   DVPANEL_UNNAMEDTABLE1Container.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_UNNAMEDTABLE1Container.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_UNNAMEDTABLE1Container.setProp("Cls", "Cls", "PanelNoHeader", "str");
   DVPANEL_UNNAMEDTABLE1Container.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_UNNAMEDTABLE1Container.setProp("Title", "Title", "", "str");
   DVPANEL_UNNAMEDTABLE1Container.setProp("Collapsible", "Collapsible", true, "bool");
   DVPANEL_UNNAMEDTABLE1Container.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_UNNAMEDTABLE1Container.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_UNNAMEDTABLE1Container.setProp("IconPosition", "Iconposition", "Right", "str");
   DVPANEL_UNNAMEDTABLE1Container.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_UNNAMEDTABLE1Container.setProp("Visible", "Visible", true, "bool");
   DVPANEL_UNNAMEDTABLE1Container.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   DVPANEL_UNNAMEDTABLE1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_UNNAMEDTABLE1Container);
   this.GRID_EMPOWERERContainer = gx.uc.getNew(this, 39, 17, "WWP_GridEmpowerer", "GRID_EMPOWERERContainer", "Grid_empowerer", "GRID_EMPOWERER");
   var GRID_EMPOWERERContainer = this.GRID_EMPOWERERContainer;
   GRID_EMPOWERERContainer.setProp("Class", "Class", "", "char");
   GRID_EMPOWERERContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRID_EMPOWERERContainer.setDynProp("GridInternalName", "Gridinternalname", "", "char");
   GRID_EMPOWERERContainer.setProp("HasCategories", "Hascategories", false, "bool");
   GRID_EMPOWERERContainer.setProp("InfiniteScrolling", "Infinitescrolling", "False", "str");
   GRID_EMPOWERERContainer.setProp("HasTitleSettings", "Hastitlesettings", false, "bool");
   GRID_EMPOWERERContainer.setProp("HasColumnsSelector", "Hascolumnsselector", false, "bool");
   GRID_EMPOWERERContainer.setProp("HasRowGroups", "Hasrowgroups", false, "bool");
   GRID_EMPOWERERContainer.setProp("FixedColumns", "Fixedcolumns", "", "str");
   GRID_EMPOWERERContainer.setProp("PopoversInGrid", "Popoversingrid", "", "str");
   GRID_EMPOWERERContainer.setProp("Visible", "Visible", true, "bool");
   GRID_EMPOWERERContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(GRID_EMPOWERERContainer);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"UNNAMEDTABLE1",grid:0};
   GXValidFnc[12]={ id: 12, fld:"",grid:0};
   GXValidFnc[13]={ id: 13, fld:"",grid:0};
   GXValidFnc[14]={ id: 14, fld:"TABLEHEADER",grid:0};
   GXValidFnc[15]={ id: 15, fld:"",grid:0};
   GXValidFnc[16]={ id: 16, fld:"",grid:0};
   GXValidFnc[17]={ id:17 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vNOTIFSHOWONLYSUBSCRIBEDEVENTS",gxz:"ZV17NotifShowOnlySubscribedEvents",gxold:"OV17NotifShowOnlySubscribedEvents",gxvar:"AV17NotifShowOnlySubscribedEvents",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"checkbox",v2v:function(Value){if(Value!==undefined)gx.O.AV17NotifShowOnlySubscribedEvents=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV17NotifShowOnlySubscribedEvents=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setCheckBoxValue("vNOTIFSHOWONLYSUBSCRIBEDEVENTS",gx.O.AV17NotifShowOnlySubscribedEvents,true)},c2v:function(){if(this.val()!==undefined)gx.O.AV17NotifShowOnlySubscribedEvents=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vNOTIFSHOWONLYSUBSCRIBEDEVENTS")},nac:gx.falseFn,evt:"e13222_client",values:['true','false']};
   GXValidFnc[18]={ id: 18, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[20]={ id:20 ,lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vFILTERFULLTEXT",gxz:"ZV7FilterFullText",gxold:"OV7FilterFullText",gxvar:"AV7FilterFullText",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV7FilterFullText=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV7FilterFullText=Value},v2c:function(){gx.fn.setControlValue("vFILTERFULLTEXT",gx.O.AV7FilterFullText,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.AV7FilterFullText=this.val()},val:function(){return gx.fn.getControlValue("vFILTERFULLTEXT")},nac:gx.falseFn};
   this.declareDomainHdlr( 20 , function() {
   });
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"",grid:0};
   GXValidFnc[23]={ id: 23, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"",grid:0};
   GXValidFnc[27]={ id:27 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:0,isacc:0,grid:26,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vWWPENTITYNAME",gxz:"ZV30WWPEntityName",gxold:"OV30WWPEntityName",gxvar:"AV30WWPEntityName",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.AV30WWPEntityName=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV30WWPEntityName=Value},v2c:function(row){gx.fn.setGridControlValue("vWWPENTITYNAME",row || gx.fn.currentGridRowImpl(26),gx.O.AV30WWPEntityName,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV30WWPEntityName=this.val(row)},val:function(row){return gx.fn.getGridControlValue("vWWPENTITYNAME",row || gx.fn.currentGridRowImpl(26))},nac:gx.falseFn};
   GXValidFnc[28]={ id:28 ,lvl:2,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,isacc:0,grid:26,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vWWPENTITYID",gxz:"ZV29WWPEntityId",gxold:"OV29WWPEntityId",gxvar:"AV29WWPEntityId",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.AV29WWPEntityId=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV29WWPEntityId=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("vWWPENTITYID",row || gx.fn.currentGridRowImpl(26),gx.O.AV29WWPEntityId,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV29WWPEntityId=gx.num.intval(this.val(row))},val:function(row){return gx.fn.getGridIntegerValue("vWWPENTITYID",row || gx.fn.currentGridRowImpl(26),'.')},nac:gx.falseFn};
   GXValidFnc[29]={ id:29 ,lvl:2,type:"char",len:20,dec:0,sign:false,ro:0,isacc:0,grid:26,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDETAILWEBCOMPONENT",gxz:"ZV6DetailWebComponent",gxold:"OV6DetailWebComponent",gxvar:"AV6DetailWebComponent",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.AV6DetailWebComponent=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV6DetailWebComponent=Value},v2c:function(row){gx.fn.setGridControlValue("vDETAILWEBCOMPONENT",row || gx.fn.currentGridRowImpl(26),gx.O.AV6DetailWebComponent,1)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV6DetailWebComponent=this.val(row)},val:function(row){return gx.fn.getGridControlValue("vDETAILWEBCOMPONENT",row || gx.fn.currentGridRowImpl(26))},nac:gx.falseFn,evt:"e17222_client"};
   GXValidFnc[30]={ id: 30, fld:"",grid:0};
   GXValidFnc[31]={ id: 31, fld:"",grid:0};
   GXValidFnc[33]={ id: 33, fld:"",grid:0};
   GXValidFnc[34]={ id: 34, fld:"CELL_GRID_DWC",grid:0};
   GXValidFnc[36]={ id: 36, fld:"",grid:0};
   GXValidFnc[37]={ id: 37, fld:"",grid:0};
   GXValidFnc[38]={ id: 38, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   this.AV17NotifShowOnlySubscribedEvents = false ;
   this.ZV17NotifShowOnlySubscribedEvents = false ;
   this.OV17NotifShowOnlySubscribedEvents = false ;
   this.AV7FilterFullText = "" ;
   this.ZV7FilterFullText = "" ;
   this.OV7FilterFullText = "" ;
   this.ZV30WWPEntityName = "" ;
   this.OV30WWPEntityName = "" ;
   this.ZV29WWPEntityId = 0 ;
   this.OV29WWPEntityId = 0 ;
   this.ZV6DetailWebComponent = "" ;
   this.OV6DetailWebComponent = "" ;
   this.AV17NotifShowOnlySubscribedEvents = false ;
   this.AV7FilterFullText = "" ;
   this.AV8GridCurrentPage = 0 ;
   this.AV36WWPSubscriptionRoleId = "" ;
   this.AV30WWPEntityName = "" ;
   this.AV29WWPEntityId = 0 ;
   this.AV6DetailWebComponent = "" ;
   this.A12WWPEntityName = "" ;
   this.A10WWPEntityId = 0 ;
   this.A40000GXC1 = 0 ;
   this.A40001GXC2 = 0 ;
   this.AV41Pgmname = "" ;
   this.Events = {"e11222_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e12222_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e13222_client": ["VNOTIFSHOWONLYSUBSCRIBEDEVENTS.CLICK", true] ,"e18222_client": ["ENTER", true] ,"e19222_client": ["CANCEL", true] ,"e17222_client": ["VDETAILWEBCOMPONENT.CLICK", false]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'A12WWPEntityName',fld:'WWPENTITYNAME',pic:''},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{ctrl:'GRID',prop:'Rows'},{av:'AV41Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV7FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'AV36WWPSubscriptionRoleId',fld:'vWWPSUBSCRIPTIONROLEID',pic:'',hsh:true},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}],[{av:'AV8GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV38GridAppliedFilters',fld:'vGRIDAPPLIEDFILTERS',pic:''},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}]];
   this.EvtParms["START"] = [[{av:'AV36WWPSubscriptionRoleId',fld:'vWWPSUBSCRIPTIONROLEID',pic:'',hsh:true},{av:'AV41Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}],[{av:'gx.fn.getCtrlProperty("CELL_GRID_DWC","Class")',ctrl:'CELL_GRID_DWC',prop:'Class'},{ctrl:'GRID',prop:'Rows'},{av:'this.GRID_EMPOWERERContainer.GridInternalName',ctrl:'GRID_EMPOWERER',prop:'GridInternalName'},{ctrl:'FORM',prop:'Caption'},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'},{av:'AV7FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV41Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'A12WWPEntityName',fld:'WWPENTITYNAME',pic:''},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV36WWPSubscriptionRoleId',fld:'vWWPSUBSCRIPTIONROLEID',pic:'',hsh:true},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV41Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV7FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'A12WWPEntityName',fld:'WWPENTITYNAME',pic:''},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV36WWPSubscriptionRoleId',fld:'vWWPSUBSCRIPTIONROLEID',pic:'',hsh:true},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}],[{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV41Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV7FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'A12WWPEntityName',fld:'WWPENTITYNAME',pic:''},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV36WWPSubscriptionRoleId',fld:'vWWPSUBSCRIPTIONROLEID',pic:'',hsh:true},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}],[{ctrl:'GRID',prop:'Rows'},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}]];
   this.EvtParms["GRID.LOAD"] = [[{av:'A12WWPEntityName',fld:'WWPENTITYNAME',pic:''},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV36WWPSubscriptionRoleId',fld:'vWWPSUBSCRIPTIONROLEID',pic:'',hsh:true},{ctrl:'GRID',prop:'Rows'},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}],[{av:'AV6DetailWebComponent',fld:'vDETAILWEBCOMPONENT',pic:''},{av:'AV30WWPEntityName',fld:'vWWPENTITYNAME',pic:''},{av:'AV29WWPEntityId',fld:'vWWPENTITYID',pic:'ZZZZZZZZZ9',hsh:true},{av:'A40000GXC1',fld:'GXC1',pic:'999999999'},{av:'A40001GXC2',fld:'GXC2',pic:'999999999'},{av:'AV9GridPageCount',fld:'vGRIDPAGECOUNT',pic:'ZZZZZZZZZ9'},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}]];
   this.EvtParms["VDETAILWEBCOMPONENT.CLICK"] = [[{av:'AV29WWPEntityId',fld:'vWWPENTITYID',pic:'ZZZZZZZZZ9',hsh:true},{av:'AV36WWPSubscriptionRoleId',fld:'vWWPSUBSCRIPTIONROLEID',pic:'',hsh:true},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}],[{ctrl:'GRID_DWC'},{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}]];
   this.EvtParms["VNOTIFSHOWONLYSUBSCRIBEDEVENTS.CLICK"] = [[{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}],[{av:'AV17NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''}]];
   this.setVCMap("AV41Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("A12WWPEntityName", "WWPENTITYNAME", 0, "svchar", 100, 0);
   this.setVCMap("A10WWPEntityId", "WWPENTITYID", 0, "int", 10, 0);
   this.setVCMap("AV36WWPSubscriptionRoleId", "vWWPSUBSCRIPTIONROLEID", 0, "char", 40, 0);
   this.setVCMap("AV41Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("A12WWPEntityName", "WWPENTITYNAME", 0, "svchar", 100, 0);
   this.setVCMap("A10WWPEntityId", "WWPENTITYID", 0, "int", 10, 0);
   this.setVCMap("AV36WWPSubscriptionRoleId", "vWWPSUBSCRIPTIONROLEID", 0, "char", 40, 0);
   this.setVCMap("AV41Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("A12WWPEntityName", "WWPENTITYNAME", 0, "svchar", 100, 0);
   this.setVCMap("A10WWPEntityId", "WWPENTITYID", 0, "int", 10, 0);
   this.setVCMap("AV36WWPSubscriptionRoleId", "vWWPSUBSCRIPTIONROLEID", 0, "char", 40, 0);
   GridContainer.addRefreshingParm({rfrProp:"Rows", gxGrid:"Grid"});
   GridContainer.addRefreshingVar({rfrVar:"AV41Pgmname"});
   GridContainer.addRefreshingVar(this.GXValidFnc[17]);
   GridContainer.addRefreshingVar(this.GXValidFnc[20]);
   GridContainer.addRefreshingVar({rfrVar:"A12WWPEntityName"});
   GridContainer.addRefreshingVar({rfrVar:"A10WWPEntityId"});
   GridContainer.addRefreshingVar({rfrVar:"AV36WWPSubscriptionRoleId"});
   GridContainer.addRefreshingParm({rfrVar:"AV41Pgmname"});
   GridContainer.addRefreshingParm(this.GXValidFnc[17]);
   GridContainer.addRefreshingParm(this.GXValidFnc[20]);
   GridContainer.addRefreshingParm({rfrVar:"A12WWPEntityName"});
   GridContainer.addRefreshingParm({rfrVar:"A10WWPEntityId"});
   GridContainer.addRefreshingParm({rfrVar:"AV36WWPSubscriptionRoleId"});
   this.Initialize( );
   this.setComponent({id: "GRID_DWC" ,GXClass: null , Prefix: "W0035" , lvl: 1 });
   this.setSDTMapping( "WWPBaseObjects\\WWPGridState" , {
      "FilterValues":{sdt:"WWPBaseObjects\\WWPGridState.FilterValue"}});
   this.setSDTMapping( "WWPBaseObjects\\WWPTransactionContext" , {
      "Attributes":{sdt:"WWPBaseObjects\\WWPTransactionContext.Attribute"}});
});
gx.wi( function() { gx.createParentObj(wwpbaseobjects.subscriptions.wwp_subscriptionssettingsbyrole);});
