gx.evt.autoSkip = false;
gx.define('wwpbaseobjects.subscriptions.wwp_subscriptionssettingswc', true, function (CmpContext) {
   this.ServerClass =  "wwpbaseobjects.subscriptions.wwp_subscriptionssettingswc" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.setCmpContext(CmpContext);
   this.ReadonlyForm = true;
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV32Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.A10WWPEntityId=gx.fn.getIntegerValue("WWPENTITYID",'.') ;
      this.AV16WWPEntityId=gx.fn.getIntegerValue("vWWPENTITYID",'.') ;
      this.A27WWPNotificationDefinitionAllowUserSubscription=gx.fn.getControlValue("WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION") ;
      this.A14WWPNotificationDefinitionId=gx.fn.getIntegerValue("WWPNOTIFICATIONDEFINITIONID",'.') ;
      this.A25WWPNotificationDefinitionDescription=gx.fn.getControlValue("WWPNOTIFICATIONDEFINITIONDESCRIPTION") ;
      this.A1WWPUserExtendedId=gx.fn.getControlValue("WWPUSEREXTENDEDID") ;
      this.AV31Udparg1=gx.fn.getControlValue("vUDPARG1") ;
      this.A23WWPSubscriptionSubscribed=gx.fn.getControlValue("WWPSUBSCRIPTIONSUBSCRIBED") ;
      this.A11WWPSubscriptionRoleId=gx.fn.getControlValue("WWPSUBSCRIPTIONROLEID") ;
      this.A13WWPSubscriptionId=gx.fn.getIntegerValue("WWPSUBSCRIPTIONID",'.') ;
      this.A26WWPNotificationDefinitionAppliesTo=gx.fn.getIntegerValue("WWPNOTIFICATIONDEFINITIONAPPLIESTO",'.') ;
      this.A22WWPSubscriptionEntityRecordId=gx.fn.getControlValue("WWPSUBSCRIPTIONENTITYRECORDID") ;
      this.A24WWPSubscriptionEntityRecordDescription=gx.fn.getControlValue("WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION") ;
      this.AV12NotifShowOnlySubscribedEvents=gx.fn.getControlValue("vNOTIFSHOWONLYSUBSCRIBEDEVENTS") ;
      this.AV32Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.A10WWPEntityId=gx.fn.getIntegerValue("WWPENTITYID",'.') ;
      this.AV16WWPEntityId=gx.fn.getIntegerValue("vWWPENTITYID",'.') ;
      this.A27WWPNotificationDefinitionAllowUserSubscription=gx.fn.getControlValue("WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION") ;
      this.A14WWPNotificationDefinitionId=gx.fn.getIntegerValue("WWPNOTIFICATIONDEFINITIONID",'.') ;
      this.A25WWPNotificationDefinitionDescription=gx.fn.getControlValue("WWPNOTIFICATIONDEFINITIONDESCRIPTION") ;
      this.A1WWPUserExtendedId=gx.fn.getControlValue("WWPUSEREXTENDEDID") ;
      this.AV31Udparg1=gx.fn.getControlValue("vUDPARG1") ;
      this.A23WWPSubscriptionSubscribed=gx.fn.getControlValue("WWPSUBSCRIPTIONSUBSCRIBED") ;
      this.A11WWPSubscriptionRoleId=gx.fn.getControlValue("WWPSUBSCRIPTIONROLEID") ;
      this.A13WWPSubscriptionId=gx.fn.getIntegerValue("WWPSUBSCRIPTIONID",'.') ;
      this.A26WWPNotificationDefinitionAppliesTo=gx.fn.getIntegerValue("WWPNOTIFICATIONDEFINITIONAPPLIESTO",'.') ;
      this.A22WWPSubscriptionEntityRecordId=gx.fn.getControlValue("WWPSUBSCRIPTIONENTITYRECORDID") ;
      this.A24WWPSubscriptionEntityRecordDescription=gx.fn.getControlValue("WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION") ;
      this.AV12NotifShowOnlySubscribedEvents=gx.fn.getControlValue("vNOTIFSHOWONLYSUBSCRIBEDEVENTS") ;
   };
   this.e15212_client=function()
   {
      return this.executeServerEvent("'FIRSTPAGE'", true, arguments[0], false, false);
   };
   this.e16212_client=function()
   {
      return this.executeServerEvent("'PREVIOUSPAGE'", true, arguments[0], false, false);
   };
   this.e17212_client=function()
   {
      return this.executeServerEvent("'NEXTPAGE'", true, arguments[0], false, false);
   };
   this.e18212_client=function()
   {
      return this.executeServerEvent("'LASTPAGE'", true, arguments[0], false, false);
   };
   this.e11212_client=function()
   {
      return this.executeServerEvent("TABLESUBSCRIPTIONITEM.CLICK", true, arguments[0], false, true);
   };
   this.e19212_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e20212_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,25,26,28,29,31,32,34,35];
   this.GXLastCtrlId =35;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",9,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.subscriptions.wwp_subscriptionssettingswc",[],true,1,false,true,0,false,false,false,"",0,"px",0,"px","Novo registro",true,false,true,null,null,false,"",true,[1,1,1,1],false,0,false,false);
   var GridContainer = this.GridContainer;
   GridContainer.startDiv(10,"Unnamedtablefsgrid","0px","0px");
   GridContainer.startDiv(11,"","0px","0px");
   GridContainer.startDiv(12,"","0px","0px");
   GridContainer.startDiv(13,"Tablesubscriptionitem","0px","0px");
   GridContainer.startDiv(14,"","0px","0px");
   GridContainer.startDiv(15,"","0px","0px");
   GridContainer.addLabel();
   GridContainer.addCheckBox("Includenotification",16,"vINCLUDENOTIFICATION","","","IncludeNotification","boolean","true","false",null,true,false,4,"chr","");
   GridContainer.endDiv();
   GridContainer.endDiv();
   GridContainer.startDiv(17,"","0px","0px");
   GridContainer.startDiv(18,"","0px","0px");
   GridContainer.addLabel();
   GridContainer.addMultipleLineEdit("Wwpnotificationdescription",19,"vWWPNOTIFICATIONDESCRIPTION","","WWPNotificationDescription","svchar",80,"chr",3,"row","200",200,"left",null,true,false,0,"");
   GridContainer.endDiv();
   GridContainer.endDiv();
   GridContainer.endDiv();
   GridContainer.endDiv();
   GridContainer.endDiv();
   GridContainer.startDiv(20,"","0px","0px");
   GridContainer.startDiv(21,"","0px","0px");
   GridContainer.startTable("Unnamedtablecontentfsgrid",22,"0px");
   GridContainer.startRow("","","","","","");
   GridContainer.startCell("","","","","","","","","","");
   GridContainer.startDiv(25,"","0px","0px");
   GridContainer.addLabel();
   GridContainer.addSingleLineEdit("Wwpnotificationdefinitionid",26,"vWWPNOTIFICATIONDEFINITIONID","","","WWPNotificationDefinitionId","int",10,"chr",10,10,"right",null,[],"Wwpnotificationdefinitionid","WWPNotificationDefinitionId",true,0,false,false,"Attribute",1,"");
   GridContainer.endDiv();
   GridContainer.endCell();
   GridContainer.startCell("","","","","","","","","","");
   GridContainer.startDiv(28,"","0px","0px");
   GridContainer.addLabel();
   GridContainer.addSingleLineEdit("Wwpsubscriptionid",29,"vWWPSUBSCRIPTIONID","","","WWPSubscriptionId","int",10,"chr",10,10,"right",null,[],"Wwpsubscriptionid","WWPSubscriptionId",true,0,false,false,"Attribute",1,"");
   GridContainer.endDiv();
   GridContainer.endCell();
   GridContainer.startCell("","","","","","","","","","");
   GridContainer.startDiv(31,"","0px","0px");
   GridContainer.addLabel();
   GridContainer.addMultipleLineEdit("Wwpsubscriptionentityrecordid",32,"vWWPSUBSCRIPTIONENTITYRECORDID","","WWPSubscriptionEntityRecordId","svchar",80,"chr",10,"row","2000",2000,"left",null,true,false,0,"");
   GridContainer.endDiv();
   GridContainer.endCell();
   GridContainer.startCell("","","","","","","","","","");
   GridContainer.startDiv(34,"","0px","0px");
   GridContainer.addLabel();
   GridContainer.addMultipleLineEdit("Wwpsubscriptionentityrecorddescription",35,"vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION","","WWPSubscriptionEntityRecordDescription","svchar",80,"chr",3,"row","200",200,"left",null,true,false,0,"");
   GridContainer.endDiv();
   GridContainer.endCell();
   GridContainer.endRow();
   GridContainer.endTable();
   GridContainer.endDiv();
   GridContainer.endDiv();
   GridContainer.endDiv();
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[10]={ id: 10, fld:"UNNAMEDTABLEFSGRID",grid:9};
   GXValidFnc[11]={ id: 11, fld:"",grid:9};
   GXValidFnc[12]={ id: 12, fld:"",grid:9};
   GXValidFnc[13]={ id: 13, fld:"TABLESUBSCRIPTIONITEM",grid:9,evt:"e11212_client"};
   GXValidFnc[14]={ id: 14, fld:"",grid:9};
   GXValidFnc[15]={ id: 15, fld:"",grid:9};
   GXValidFnc[16]={ id:16 ,lvl:2,type:"boolean",len:4,dec:0,sign:false,ro:0,isacc:0,grid:9,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vINCLUDENOTIFICATION",gxz:"ZV11IncludeNotification",gxold:"OV11IncludeNotification",gxvar:"AV11IncludeNotification",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV11IncludeNotification=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV11IncludeNotification=gx.lang.booleanValue(Value)},v2c:function(row){gx.fn.setGridCheckBoxValue("vINCLUDENOTIFICATION",row || gx.fn.currentGridRowImpl(9),gx.O.AV11IncludeNotification,true)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV11IncludeNotification=gx.lang.booleanValue(this.val(row))},val:function(row){return gx.fn.getGridControlValue("vINCLUDENOTIFICATION",row || gx.fn.currentGridRowImpl(9))},nac:gx.falseFn,values:['true','false']};
   GXValidFnc[17]={ id: 17, fld:"",grid:9};
   GXValidFnc[18]={ id: 18, fld:"",grid:9};
   GXValidFnc[19]={ id:19 ,lvl:2,type:"svchar",len:200,dec:0,sign:false,ro:0,isacc:0, multiline:true,grid:9,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vWWPNOTIFICATIONDESCRIPTION",gxz:"ZV17WWPNotificationDescription",gxold:"OV17WWPNotificationDescription",gxvar:"AV17WWPNotificationDescription",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.AV17WWPNotificationDescription=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV17WWPNotificationDescription=Value},v2c:function(row){gx.fn.setGridControlValue("vWWPNOTIFICATIONDESCRIPTION",row || gx.fn.currentGridRowImpl(9),gx.O.AV17WWPNotificationDescription,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV17WWPNotificationDescription=this.val(row)},val:function(row){return gx.fn.getGridControlValue("vWWPNOTIFICATIONDESCRIPTION",row || gx.fn.currentGridRowImpl(9))},nac:gx.falseFn};
   GXValidFnc[20]={ id: 20, fld:"",grid:9};
   GXValidFnc[21]={ id: 21, fld:"",grid:9};
   GXValidFnc[22]={ id: 22, fld:"UNNAMEDTABLECONTENTFSGRID",grid:9};
   GXValidFnc[25]={ id: 25, fld:"",grid:9};
   GXValidFnc[26]={ id:26 ,lvl:2,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,isacc:0,grid:9,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vWWPNOTIFICATIONDEFINITIONID",gxz:"ZV5WWPNotificationDefinitionId",gxold:"OV5WWPNotificationDefinitionId",gxvar:"AV5WWPNotificationDefinitionId",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.AV5WWPNotificationDefinitionId=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV5WWPNotificationDefinitionId=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("vWWPNOTIFICATIONDEFINITIONID",row || gx.fn.currentGridRowImpl(9),gx.O.AV5WWPNotificationDefinitionId,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV5WWPNotificationDefinitionId=gx.num.intval(this.val(row))},val:function(row){return gx.fn.getGridIntegerValue("vWWPNOTIFICATIONDEFINITIONID",row || gx.fn.currentGridRowImpl(9),'.')},nac:gx.falseFn};
   GXValidFnc[28]={ id: 28, fld:"",grid:9};
   GXValidFnc[29]={ id:29 ,lvl:2,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,isacc:0,grid:9,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vWWPSUBSCRIPTIONID",gxz:"ZV7WWPSubscriptionId",gxold:"OV7WWPSubscriptionId",gxvar:"AV7WWPSubscriptionId",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.AV7WWPSubscriptionId=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV7WWPSubscriptionId=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("vWWPSUBSCRIPTIONID",row || gx.fn.currentGridRowImpl(9),gx.O.AV7WWPSubscriptionId,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV7WWPSubscriptionId=gx.num.intval(this.val(row))},val:function(row){return gx.fn.getGridIntegerValue("vWWPSUBSCRIPTIONID",row || gx.fn.currentGridRowImpl(9),'.')},nac:gx.falseFn};
   GXValidFnc[31]={ id: 31, fld:"",grid:9};
   GXValidFnc[32]={ id:32 ,lvl:2,type:"svchar",len:2000,dec:0,sign:false,ro:0,isacc:0, multiline:true,grid:9,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vWWPSUBSCRIPTIONENTITYRECORDID",gxz:"ZV19WWPSubscriptionEntityRecordId",gxold:"OV19WWPSubscriptionEntityRecordId",gxvar:"AV19WWPSubscriptionEntityRecordId",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.AV19WWPSubscriptionEntityRecordId=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV19WWPSubscriptionEntityRecordId=Value},v2c:function(row){gx.fn.setGridControlValue("vWWPSUBSCRIPTIONENTITYRECORDID",row || gx.fn.currentGridRowImpl(9),gx.O.AV19WWPSubscriptionEntityRecordId,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV19WWPSubscriptionEntityRecordId=this.val(row)},val:function(row){return gx.fn.getGridControlValue("vWWPSUBSCRIPTIONENTITYRECORDID",row || gx.fn.currentGridRowImpl(9))},nac:gx.falseFn};
   GXValidFnc[34]={ id: 34, fld:"",grid:9};
   GXValidFnc[35]={ id:35 ,lvl:2,type:"svchar",len:200,dec:0,sign:false,ro:0,isacc:0, multiline:true,grid:9,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION",gxz:"ZV6WWPSubscriptionEntityRecordDescription",gxold:"OV6WWPSubscriptionEntityRecordDescription",gxvar:"AV6WWPSubscriptionEntityRecordDescription",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.AV6WWPSubscriptionEntityRecordDescription=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV6WWPSubscriptionEntityRecordDescription=Value},v2c:function(row){gx.fn.setGridControlValue("vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION",row || gx.fn.currentGridRowImpl(9),gx.O.AV6WWPSubscriptionEntityRecordDescription,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV6WWPSubscriptionEntityRecordDescription=this.val(row)},val:function(row){return gx.fn.getGridControlValue("vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION",row || gx.fn.currentGridRowImpl(9))},nac:gx.falseFn};
   this.ZV11IncludeNotification = false ;
   this.OV11IncludeNotification = false ;
   this.ZV17WWPNotificationDescription = "" ;
   this.OV17WWPNotificationDescription = "" ;
   this.ZV5WWPNotificationDefinitionId = 0 ;
   this.OV5WWPNotificationDefinitionId = 0 ;
   this.ZV7WWPSubscriptionId = 0 ;
   this.OV7WWPSubscriptionId = 0 ;
   this.ZV19WWPSubscriptionEntityRecordId = "" ;
   this.OV19WWPSubscriptionEntityRecordId = "" ;
   this.ZV6WWPSubscriptionEntityRecordDescription = "" ;
   this.OV6WWPSubscriptionEntityRecordDescription = "" ;
   this.AV16WWPEntityId = 0 ;
   this.AV12NotifShowOnlySubscribedEvents = false ;
   this.AV11IncludeNotification = false ;
   this.AV17WWPNotificationDescription = "" ;
   this.AV5WWPNotificationDefinitionId = 0 ;
   this.AV7WWPSubscriptionId = 0 ;
   this.AV19WWPSubscriptionEntityRecordId = "" ;
   this.AV6WWPSubscriptionEntityRecordDescription = "" ;
   this.A14WWPNotificationDefinitionId = 0 ;
   this.A26WWPNotificationDefinitionAppliesTo = 0 ;
   this.A27WWPNotificationDefinitionAllowUserSubscription = false ;
   this.A10WWPEntityId = 0 ;
   this.A25WWPNotificationDefinitionDescription = "" ;
   this.A11WWPSubscriptionRoleId = "" ;
   this.A23WWPSubscriptionSubscribed = false ;
   this.A1WWPUserExtendedId = "" ;
   this.A13WWPSubscriptionId = 0 ;
   this.A22WWPSubscriptionEntityRecordId = "" ;
   this.A24WWPSubscriptionEntityRecordDescription = "" ;
   this.AV32Pgmname = "" ;
   this.AV31Udparg1 = "" ;
   this.Events = {"e15212_client": ["'FIRSTPAGE'", true] ,"e16212_client": ["'PREVIOUSPAGE'", true] ,"e17212_client": ["'NEXTPAGE'", true] ,"e18212_client": ["'LASTPAGE'", true] ,"e11212_client": ["TABLESUBSCRIPTIONITEM.CLICK", true] ,"e19212_client": ["ENTER", true] ,"e20212_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'gx.fn.getCtrlProperty("vWWPNOTIFICATIONDEFINITIONID","Visible")',ctrl:'vWWPNOTIFICATIONDEFINITIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONID","Visible")',ctrl:'vWWPSUBSCRIPTIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDID","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',prop:'Visible'},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV16WWPEntityId',fld:'vWWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'A27WWPNotificationDefinitionAllowUserSubscription',fld:'WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION',pic:''},{av:'A14WWPNotificationDefinitionId',fld:'WWPNOTIFICATIONDEFINITIONID',pic:'ZZZZZZZZZ9'},{av:'A25WWPNotificationDefinitionDescription',fld:'WWPNOTIFICATIONDEFINITIONDESCRIPTION',pic:''},{av:'A1WWPUserExtendedId',fld:'WWPUSEREXTENDEDID',pic:''},{av:'A23WWPSubscriptionSubscribed',fld:'WWPSUBSCRIPTIONSUBSCRIBED',pic:''},{av:'A11WWPSubscriptionRoleId',fld:'WWPSUBSCRIPTIONROLEID',pic:''},{av:'A13WWPSubscriptionId',fld:'WWPSUBSCRIPTIONID',pic:'ZZZZZZZZZ9'},{av:'A26WWPNotificationDefinitionAppliesTo',fld:'WWPNOTIFICATIONDEFINITIONAPPLIESTO',pic:'9'},{av:'A22WWPSubscriptionEntityRecordId',fld:'WWPSUBSCRIPTIONENTITYRECORDID',pic:''},{av:'A24WWPSubscriptionEntityRecordDescription',fld:'WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',pic:''},{av:'AV12NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''},{av:'sPrefix'},{ctrl:'GRID',prop:'Rows'},{av:'AV32Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV31Udparg1',fld:'vUDPARG1',pic:'',hsh:true}],[]];
   this.EvtParms["START"] = [[{av:'AV32Pgmname',fld:'vPGMNAME',pic:'',hsh:true}],[{av:'gx.fn.getCtrlProperty("vWWPNOTIFICATIONDEFINITIONID","Visible")',ctrl:'vWWPNOTIFICATIONDEFINITIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONID","Visible")',ctrl:'vWWPSUBSCRIPTIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDID","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',prop:'Visible'},{ctrl:'GRID',prop:'Rows'},{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV32Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV16WWPEntityId',fld:'vWWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'A27WWPNotificationDefinitionAllowUserSubscription',fld:'WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION',pic:''},{av:'A14WWPNotificationDefinitionId',fld:'WWPNOTIFICATIONDEFINITIONID',pic:'ZZZZZZZZZ9'},{av:'A25WWPNotificationDefinitionDescription',fld:'WWPNOTIFICATIONDEFINITIONDESCRIPTION',pic:''},{av:'A1WWPUserExtendedId',fld:'WWPUSEREXTENDEDID',pic:''},{av:'AV31Udparg1',fld:'vUDPARG1',pic:'',hsh:true},{av:'A23WWPSubscriptionSubscribed',fld:'WWPSUBSCRIPTIONSUBSCRIBED',pic:''},{av:'A11WWPSubscriptionRoleId',fld:'WWPSUBSCRIPTIONROLEID',pic:''},{av:'A13WWPSubscriptionId',fld:'WWPSUBSCRIPTIONID',pic:'ZZZZZZZZZ9'},{av:'A26WWPNotificationDefinitionAppliesTo',fld:'WWPNOTIFICATIONDEFINITIONAPPLIESTO',pic:'9'},{av:'A22WWPSubscriptionEntityRecordId',fld:'WWPSUBSCRIPTIONENTITYRECORDID',pic:''},{av:'A24WWPSubscriptionEntityRecordDescription',fld:'WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',pic:''},{av:'AV12NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''},{av:'sPrefix'}]];
   this.EvtParms["GRID.LOAD"] = [[{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV16WWPEntityId',fld:'vWWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'A27WWPNotificationDefinitionAllowUserSubscription',fld:'WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION',pic:''},{av:'A14WWPNotificationDefinitionId',fld:'WWPNOTIFICATIONDEFINITIONID',pic:'ZZZZZZZZZ9'},{av:'A25WWPNotificationDefinitionDescription',fld:'WWPNOTIFICATIONDEFINITIONDESCRIPTION',pic:''},{av:'A1WWPUserExtendedId',fld:'WWPUSEREXTENDEDID',pic:''},{av:'AV31Udparg1',fld:'vUDPARG1',pic:'',hsh:true},{av:'A23WWPSubscriptionSubscribed',fld:'WWPSUBSCRIPTIONSUBSCRIBED',pic:''},{av:'A11WWPSubscriptionRoleId',fld:'WWPSUBSCRIPTIONROLEID',pic:''},{av:'A13WWPSubscriptionId',fld:'WWPSUBSCRIPTIONID',pic:'ZZZZZZZZZ9'},{av:'A26WWPNotificationDefinitionAppliesTo',fld:'WWPNOTIFICATIONDEFINITIONAPPLIESTO',pic:'9'},{av:'A22WWPSubscriptionEntityRecordId',fld:'WWPSUBSCRIPTIONENTITYRECORDID',pic:''},{av:'A24WWPSubscriptionEntityRecordDescription',fld:'WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',pic:''},{av:'AV12NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''},{ctrl:'GRID',prop:'Rows'}],[{av:'AV5WWPNotificationDefinitionId',fld:'vWWPNOTIFICATIONDEFINITIONID',pic:'ZZZZZZZZZ9'},{av:'AV17WWPNotificationDescription',fld:'vWWPNOTIFICATIONDESCRIPTION',pic:''},{av:'AV11IncludeNotification',fld:'vINCLUDENOTIFICATION',pic:''},{av:'AV7WWPSubscriptionId',fld:'vWWPSUBSCRIPTIONID',pic:'ZZZZZZZZZ9'},{av:'AV6WWPSubscriptionEntityRecordDescription',fld:'vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',pic:''},{av:'AV19WWPSubscriptionEntityRecordId',fld:'vWWPSUBSCRIPTIONENTITYRECORDID',pic:''}]];
   this.EvtParms["'FIRSTPAGE'"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV32Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'gx.fn.getCtrlProperty("vWWPNOTIFICATIONDEFINITIONID","Visible")',ctrl:'vWWPNOTIFICATIONDEFINITIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONID","Visible")',ctrl:'vWWPSUBSCRIPTIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDID","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',prop:'Visible'},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV16WWPEntityId',fld:'vWWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'A27WWPNotificationDefinitionAllowUserSubscription',fld:'WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION',pic:''},{av:'A14WWPNotificationDefinitionId',fld:'WWPNOTIFICATIONDEFINITIONID',pic:'ZZZZZZZZZ9'},{av:'A25WWPNotificationDefinitionDescription',fld:'WWPNOTIFICATIONDEFINITIONDESCRIPTION',pic:''},{av:'A1WWPUserExtendedId',fld:'WWPUSEREXTENDEDID',pic:''},{av:'AV31Udparg1',fld:'vUDPARG1',pic:'',hsh:true},{av:'A23WWPSubscriptionSubscribed',fld:'WWPSUBSCRIPTIONSUBSCRIBED',pic:''},{av:'A11WWPSubscriptionRoleId',fld:'WWPSUBSCRIPTIONROLEID',pic:''},{av:'A13WWPSubscriptionId',fld:'WWPSUBSCRIPTIONID',pic:'ZZZZZZZZZ9'},{av:'A26WWPNotificationDefinitionAppliesTo',fld:'WWPNOTIFICATIONDEFINITIONAPPLIESTO',pic:'9'},{av:'A22WWPSubscriptionEntityRecordId',fld:'WWPSUBSCRIPTIONENTITYRECORDID',pic:''},{av:'A24WWPSubscriptionEntityRecordDescription',fld:'WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',pic:''},{av:'AV12NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''},{av:'sPrefix'}],[]];
   this.EvtParms["'PREVIOUSPAGE'"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV32Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'gx.fn.getCtrlProperty("vWWPNOTIFICATIONDEFINITIONID","Visible")',ctrl:'vWWPNOTIFICATIONDEFINITIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONID","Visible")',ctrl:'vWWPSUBSCRIPTIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDID","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',prop:'Visible'},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV16WWPEntityId',fld:'vWWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'A27WWPNotificationDefinitionAllowUserSubscription',fld:'WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION',pic:''},{av:'A14WWPNotificationDefinitionId',fld:'WWPNOTIFICATIONDEFINITIONID',pic:'ZZZZZZZZZ9'},{av:'A25WWPNotificationDefinitionDescription',fld:'WWPNOTIFICATIONDEFINITIONDESCRIPTION',pic:''},{av:'A1WWPUserExtendedId',fld:'WWPUSEREXTENDEDID',pic:''},{av:'AV31Udparg1',fld:'vUDPARG1',pic:'',hsh:true},{av:'A23WWPSubscriptionSubscribed',fld:'WWPSUBSCRIPTIONSUBSCRIBED',pic:''},{av:'A11WWPSubscriptionRoleId',fld:'WWPSUBSCRIPTIONROLEID',pic:''},{av:'A13WWPSubscriptionId',fld:'WWPSUBSCRIPTIONID',pic:'ZZZZZZZZZ9'},{av:'A26WWPNotificationDefinitionAppliesTo',fld:'WWPNOTIFICATIONDEFINITIONAPPLIESTO',pic:'9'},{av:'A22WWPSubscriptionEntityRecordId',fld:'WWPSUBSCRIPTIONENTITYRECORDID',pic:''},{av:'A24WWPSubscriptionEntityRecordDescription',fld:'WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',pic:''},{av:'AV12NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''},{av:'sPrefix'}],[]];
   this.EvtParms["'NEXTPAGE'"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV32Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'gx.fn.getCtrlProperty("vWWPNOTIFICATIONDEFINITIONID","Visible")',ctrl:'vWWPNOTIFICATIONDEFINITIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONID","Visible")',ctrl:'vWWPSUBSCRIPTIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDID","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',prop:'Visible'},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV16WWPEntityId',fld:'vWWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'A27WWPNotificationDefinitionAllowUserSubscription',fld:'WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION',pic:''},{av:'A14WWPNotificationDefinitionId',fld:'WWPNOTIFICATIONDEFINITIONID',pic:'ZZZZZZZZZ9'},{av:'A25WWPNotificationDefinitionDescription',fld:'WWPNOTIFICATIONDEFINITIONDESCRIPTION',pic:''},{av:'A1WWPUserExtendedId',fld:'WWPUSEREXTENDEDID',pic:''},{av:'AV31Udparg1',fld:'vUDPARG1',pic:'',hsh:true},{av:'A23WWPSubscriptionSubscribed',fld:'WWPSUBSCRIPTIONSUBSCRIBED',pic:''},{av:'A11WWPSubscriptionRoleId',fld:'WWPSUBSCRIPTIONROLEID',pic:''},{av:'A13WWPSubscriptionId',fld:'WWPSUBSCRIPTIONID',pic:'ZZZZZZZZZ9'},{av:'A26WWPNotificationDefinitionAppliesTo',fld:'WWPNOTIFICATIONDEFINITIONAPPLIESTO',pic:'9'},{av:'A22WWPSubscriptionEntityRecordId',fld:'WWPSUBSCRIPTIONENTITYRECORDID',pic:''},{av:'A24WWPSubscriptionEntityRecordDescription',fld:'WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',pic:''},{av:'AV12NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''},{av:'sPrefix'}],[]];
   this.EvtParms["'LASTPAGE'"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV32Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'gx.fn.getCtrlProperty("vWWPNOTIFICATIONDEFINITIONID","Visible")',ctrl:'vWWPNOTIFICATIONDEFINITIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONID","Visible")',ctrl:'vWWPSUBSCRIPTIONID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDID","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION","Visible")',ctrl:'vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',prop:'Visible'},{av:'A10WWPEntityId',fld:'WWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'AV16WWPEntityId',fld:'vWWPENTITYID',pic:'ZZZZZZZZZ9'},{av:'A27WWPNotificationDefinitionAllowUserSubscription',fld:'WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION',pic:''},{av:'A14WWPNotificationDefinitionId',fld:'WWPNOTIFICATIONDEFINITIONID',pic:'ZZZZZZZZZ9'},{av:'A25WWPNotificationDefinitionDescription',fld:'WWPNOTIFICATIONDEFINITIONDESCRIPTION',pic:''},{av:'A1WWPUserExtendedId',fld:'WWPUSEREXTENDEDID',pic:''},{av:'AV31Udparg1',fld:'vUDPARG1',pic:'',hsh:true},{av:'A23WWPSubscriptionSubscribed',fld:'WWPSUBSCRIPTIONSUBSCRIBED',pic:''},{av:'A11WWPSubscriptionRoleId',fld:'WWPSUBSCRIPTIONROLEID',pic:''},{av:'A13WWPSubscriptionId',fld:'WWPSUBSCRIPTIONID',pic:'ZZZZZZZZZ9'},{av:'A26WWPNotificationDefinitionAppliesTo',fld:'WWPNOTIFICATIONDEFINITIONAPPLIESTO',pic:'9'},{av:'A22WWPSubscriptionEntityRecordId',fld:'WWPSUBSCRIPTIONENTITYRECORDID',pic:''},{av:'A24WWPSubscriptionEntityRecordDescription',fld:'WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',pic:''},{av:'AV12NotifShowOnlySubscribedEvents',fld:'vNOTIFSHOWONLYSUBSCRIBEDEVENTS',pic:''},{av:'sPrefix'}],[]];
   this.EvtParms["TABLESUBSCRIPTIONITEM.CLICK"] = [[{av:'AV11IncludeNotification',fld:'vINCLUDENOTIFICATION',grid:9,pic:''},{av:'GRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_9',ctrl:'GRID',grid:9,prop:'GridRC'},{av:'AV7WWPSubscriptionId',fld:'vWWPSUBSCRIPTIONID',grid:9,pic:'ZZZZZZZZZ9'},{av:'AV5WWPNotificationDefinitionId',fld:'vWWPNOTIFICATIONDEFINITIONID',grid:9,pic:'ZZZZZZZZZ9'},{av:'AV19WWPSubscriptionEntityRecordId',fld:'vWWPSUBSCRIPTIONENTITYRECORDID',grid:9,pic:''},{av:'AV6WWPSubscriptionEntityRecordDescription',fld:'vWWPSUBSCRIPTIONENTITYRECORDDESCRIPTION',grid:9,pic:''}],[{av:'AV11IncludeNotification',fld:'vINCLUDENOTIFICATION',pic:''},{av:'AV7WWPSubscriptionId',fld:'vWWPSUBSCRIPTIONID',pic:'ZZZZZZZZZ9'}]];
   this.setVCMap("AV32Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("A10WWPEntityId", "WWPENTITYID", 0, "int", 10, 0);
   this.setVCMap("AV16WWPEntityId", "vWWPENTITYID", 0, "int", 10, 0);
   this.setVCMap("A27WWPNotificationDefinitionAllowUserSubscription", "WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION", 0, "boolean", 4, 0);
   this.setVCMap("A14WWPNotificationDefinitionId", "WWPNOTIFICATIONDEFINITIONID", 0, "int", 10, 0);
   this.setVCMap("A25WWPNotificationDefinitionDescription", "WWPNOTIFICATIONDEFINITIONDESCRIPTION", 0, "svchar", 200, 0);
   this.setVCMap("A1WWPUserExtendedId", "WWPUSEREXTENDEDID", 0, "char", 40, 0);
   this.setVCMap("AV31Udparg1", "vUDPARG1", 0, "char", 40, 0);
   this.setVCMap("A23WWPSubscriptionSubscribed", "WWPSUBSCRIPTIONSUBSCRIBED", 0, "boolean", 4, 0);
   this.setVCMap("A11WWPSubscriptionRoleId", "WWPSUBSCRIPTIONROLEID", 0, "char", 40, 0);
   this.setVCMap("A13WWPSubscriptionId", "WWPSUBSCRIPTIONID", 0, "int", 10, 0);
   this.setVCMap("A26WWPNotificationDefinitionAppliesTo", "WWPNOTIFICATIONDEFINITIONAPPLIESTO", 0, "int", 1, 0);
   this.setVCMap("A22WWPSubscriptionEntityRecordId", "WWPSUBSCRIPTIONENTITYRECORDID", 0, "svchar", 2000, 0);
   this.setVCMap("A24WWPSubscriptionEntityRecordDescription", "WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION", 0, "svchar", 200, 0);
   this.setVCMap("AV12NotifShowOnlySubscribedEvents", "vNOTIFSHOWONLYSUBSCRIBEDEVENTS", 0, "boolean", 4, 0);
   this.setVCMap("AV32Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("A10WWPEntityId", "WWPENTITYID", 0, "int", 10, 0);
   this.setVCMap("AV16WWPEntityId", "vWWPENTITYID", 0, "int", 10, 0);
   this.setVCMap("A27WWPNotificationDefinitionAllowUserSubscription", "WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION", 0, "boolean", 4, 0);
   this.setVCMap("A14WWPNotificationDefinitionId", "WWPNOTIFICATIONDEFINITIONID", 0, "int", 10, 0);
   this.setVCMap("A25WWPNotificationDefinitionDescription", "WWPNOTIFICATIONDEFINITIONDESCRIPTION", 0, "svchar", 200, 0);
   this.setVCMap("A1WWPUserExtendedId", "WWPUSEREXTENDEDID", 0, "char", 40, 0);
   this.setVCMap("AV31Udparg1", "vUDPARG1", 0, "char", 40, 0);
   this.setVCMap("A23WWPSubscriptionSubscribed", "WWPSUBSCRIPTIONSUBSCRIBED", 0, "boolean", 4, 0);
   this.setVCMap("A11WWPSubscriptionRoleId", "WWPSUBSCRIPTIONROLEID", 0, "char", 40, 0);
   this.setVCMap("A13WWPSubscriptionId", "WWPSUBSCRIPTIONID", 0, "int", 10, 0);
   this.setVCMap("A26WWPNotificationDefinitionAppliesTo", "WWPNOTIFICATIONDEFINITIONAPPLIESTO", 0, "int", 1, 0);
   this.setVCMap("A22WWPSubscriptionEntityRecordId", "WWPSUBSCRIPTIONENTITYRECORDID", 0, "svchar", 2000, 0);
   this.setVCMap("A24WWPSubscriptionEntityRecordDescription", "WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION", 0, "svchar", 200, 0);
   this.setVCMap("AV12NotifShowOnlySubscribedEvents", "vNOTIFSHOWONLYSUBSCRIBEDEVENTS", 0, "boolean", 4, 0);
   this.setVCMap("AV32Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("A10WWPEntityId", "WWPENTITYID", 0, "int", 10, 0);
   this.setVCMap("AV16WWPEntityId", "vWWPENTITYID", 0, "int", 10, 0);
   this.setVCMap("A27WWPNotificationDefinitionAllowUserSubscription", "WWPNOTIFICATIONDEFINITIONALLOWUSERSUBSCRIPTION", 0, "boolean", 4, 0);
   this.setVCMap("A14WWPNotificationDefinitionId", "WWPNOTIFICATIONDEFINITIONID", 0, "int", 10, 0);
   this.setVCMap("A25WWPNotificationDefinitionDescription", "WWPNOTIFICATIONDEFINITIONDESCRIPTION", 0, "svchar", 200, 0);
   this.setVCMap("A1WWPUserExtendedId", "WWPUSEREXTENDEDID", 0, "char", 40, 0);
   this.setVCMap("AV31Udparg1", "vUDPARG1", 0, "char", 40, 0);
   this.setVCMap("A23WWPSubscriptionSubscribed", "WWPSUBSCRIPTIONSUBSCRIBED", 0, "boolean", 4, 0);
   this.setVCMap("A11WWPSubscriptionRoleId", "WWPSUBSCRIPTIONROLEID", 0, "char", 40, 0);
   this.setVCMap("A13WWPSubscriptionId", "WWPSUBSCRIPTIONID", 0, "int", 10, 0);
   this.setVCMap("A26WWPNotificationDefinitionAppliesTo", "WWPNOTIFICATIONDEFINITIONAPPLIESTO", 0, "int", 1, 0);
   this.setVCMap("A22WWPSubscriptionEntityRecordId", "WWPSUBSCRIPTIONENTITYRECORDID", 0, "svchar", 2000, 0);
   this.setVCMap("A24WWPSubscriptionEntityRecordDescription", "WWPSUBSCRIPTIONENTITYRECORDDESCRIPTION", 0, "svchar", 200, 0);
   this.setVCMap("AV12NotifShowOnlySubscribedEvents", "vNOTIFSHOWONLYSUBSCRIBEDEVENTS", 0, "boolean", 4, 0);
   GridContainer.addRefreshingParm({rfrProp:"Rows", gxGrid:"Grid"});
   GridContainer.addRefreshingVar({rfrVar:"AV32Pgmname"});
   GridContainer.addRefreshingVar({rfrVar:"AV5WWPNotificationDefinitionId", rfrProp:"Visible", gxAttId:"Wwpnotificationdefinitionid"});
   GridContainer.addRefreshingVar({rfrVar:"AV7WWPSubscriptionId", rfrProp:"Visible", gxAttId:"Wwpsubscriptionid"});
   GridContainer.addRefreshingVar({rfrVar:"AV19WWPSubscriptionEntityRecordId", rfrProp:"Visible", gxAttId:"Wwpsubscriptionentityrecordid"});
   GridContainer.addRefreshingVar({rfrVar:"AV6WWPSubscriptionEntityRecordDescription", rfrProp:"Visible", gxAttId:"Wwpsubscriptionentityrecorddescription"});
   GridContainer.addRefreshingVar({rfrVar:"A10WWPEntityId"});
   GridContainer.addRefreshingVar({rfrVar:"AV16WWPEntityId"});
   GridContainer.addRefreshingVar({rfrVar:"A27WWPNotificationDefinitionAllowUserSubscription"});
   GridContainer.addRefreshingVar({rfrVar:"A14WWPNotificationDefinitionId"});
   GridContainer.addRefreshingVar({rfrVar:"A25WWPNotificationDefinitionDescription"});
   GridContainer.addRefreshingVar({rfrVar:"A1WWPUserExtendedId"});
   GridContainer.addRefreshingVar({rfrVar:"AV31Udparg1"});
   GridContainer.addRefreshingVar({rfrVar:"A23WWPSubscriptionSubscribed"});
   GridContainer.addRefreshingVar({rfrVar:"A11WWPSubscriptionRoleId"});
   GridContainer.addRefreshingVar({rfrVar:"A13WWPSubscriptionId"});
   GridContainer.addRefreshingVar({rfrVar:"A26WWPNotificationDefinitionAppliesTo"});
   GridContainer.addRefreshingVar({rfrVar:"A22WWPSubscriptionEntityRecordId"});
   GridContainer.addRefreshingVar({rfrVar:"A24WWPSubscriptionEntityRecordDescription"});
   GridContainer.addRefreshingVar({rfrVar:"AV12NotifShowOnlySubscribedEvents"});
   GridContainer.addRefreshingParm({rfrVar:"AV32Pgmname"});
   GridContainer.addRefreshingParm({rfrVar:"AV5WWPNotificationDefinitionId", rfrProp:"Visible", gxAttId:"Wwpnotificationdefinitionid"});
   GridContainer.addRefreshingParm({rfrVar:"AV7WWPSubscriptionId", rfrProp:"Visible", gxAttId:"Wwpsubscriptionid"});
   GridContainer.addRefreshingParm({rfrVar:"AV19WWPSubscriptionEntityRecordId", rfrProp:"Visible", gxAttId:"Wwpsubscriptionentityrecordid"});
   GridContainer.addRefreshingParm({rfrVar:"AV6WWPSubscriptionEntityRecordDescription", rfrProp:"Visible", gxAttId:"Wwpsubscriptionentityrecorddescription"});
   GridContainer.addRefreshingParm({rfrVar:"A10WWPEntityId"});
   GridContainer.addRefreshingParm({rfrVar:"AV16WWPEntityId"});
   GridContainer.addRefreshingParm({rfrVar:"A27WWPNotificationDefinitionAllowUserSubscription"});
   GridContainer.addRefreshingParm({rfrVar:"A14WWPNotificationDefinitionId"});
   GridContainer.addRefreshingParm({rfrVar:"A25WWPNotificationDefinitionDescription"});
   GridContainer.addRefreshingParm({rfrVar:"A1WWPUserExtendedId"});
   GridContainer.addRefreshingParm({rfrVar:"AV31Udparg1"});
   GridContainer.addRefreshingParm({rfrVar:"A23WWPSubscriptionSubscribed"});
   GridContainer.addRefreshingParm({rfrVar:"A11WWPSubscriptionRoleId"});
   GridContainer.addRefreshingParm({rfrVar:"A13WWPSubscriptionId"});
   GridContainer.addRefreshingParm({rfrVar:"A26WWPNotificationDefinitionAppliesTo"});
   GridContainer.addRefreshingParm({rfrVar:"A22WWPSubscriptionEntityRecordId"});
   GridContainer.addRefreshingParm({rfrVar:"A24WWPSubscriptionEntityRecordDescription"});
   GridContainer.addRefreshingParm({rfrVar:"AV12NotifShowOnlySubscribedEvents"});
   this.Initialize( );
   this.setSDTMapping( "WWPBaseObjects\\WWPGridState" , {
      "FilterValues":{sdt:"WWPBaseObjects\\WWPGridState.FilterValue"}});
});
